name: Publish PowerShell Module

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Prepare NuGet and PSGallery
      shell: pwsh
      run: |
          If (!(Get-PackageProvider | Where-Object { $_.Name -eq 'NuGet' })) {
              Install-PackageProvider -Name NuGet -force | Out-Null
          }
          Import-PackageProvider -Name NuGet -force | Out-Null
          If ((Get-PSRepository -Name PSGallery).InstallationPolicy -ne 'Trusted') {
              Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          }
    - name: Publish Module to PowerShell Gallery
      env:
        PKG_VER: ${{ github.event.release.tag_name }}
        NUGET_KEY: ${{ secrets.PS_GALLERY_KEY }}
        MANIFEST: ./DevOps.Helper.Functions.psd1
        PUB_FUNC: ./Public
        MODULE_PATH: ${{ github.workspace }}
      shell: pwsh
      run: |
          $Manifest = (Get-Content -Path $env:MANIFEST -Raw) -replace '0.0.0', $env:PKG_VER
          If ((Test-Path -Path $env:PUB_FUNC) -and ($PublicNames = Get-ChildItem -Path $env:PUB_FUNC -Filter '*.ps1' | Select-Object -ExpandProperty BaseName)) {
              $FuncToExport = "'$($PublicNames -join "','")'"
          }
          Else {
              $FuncToExport = $null
          }

          $Manifest = $Manifest -replace "'<FunctionsToExport>'", $FuncToExport
          $Manifest | Set-Content -Path $env:MANIFEST

          Write-Host $(Get-Content -Path $env:MANIFEST -Raw)

          Publish-Module -Path $env:MODULE_PATH -NuGetApiKey $env:NUGET_KEY -Verbose
