name: Publish PowerShell Module

on:
  push:
    branches: 
      - main
    paths:
      - DevOps.Helper.Functions.psd1

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Publish Module to PowerShell Gallery
      run: |
          Publish-Module -Path .\ -NuGetApiKey $env:POWERSHELLGALLERY_KEY
      shell: pwsh
      env:
          POWERSHELLGALLERY_KEY: ${{ secrets.PS_GALLERY_KEY }}
